# mrge Task

## Data Ingestion

### Import Csv Data to pandas data frame

In [1]:
import pandas as pd
import numpy as np

In [6]:
dim_product_df = pd.read_excel("/Users/abhisheksingh/Downloads/archive/Data Analysts - Tableau Home Test - Data.xlsx", sheet_name="Dim Product")
dim_customer_df = pd.read_excel("/Users/abhisheksingh/Downloads/archive/Data Analysts - Tableau Home Test - Data.xlsx", sheet_name="Dim Customer")
dim_order_df = pd.read_excel("/Users/abhisheksingh/Downloads/archive/Data Analysts - Tableau Home Test - Data.xlsx", sheet_name="Dim Order")
fact_sales_df = pd.read_excel("/Users/abhisheksingh/Downloads/archive/Data Analysts - Tableau Home Test - Data.xlsx", sheet_name="Fact Sales")

In [17]:
dim_product_df.info()
dim_product_df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1862 entries, 0 to 1861
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Dim Product ID  1862 non-null   int64
 1   Product ID      1862 non-null   object
 2   Product Type    1862 non-null   object
 3   Sub-Category    1862 non-null   object
 4   Product Name    1862 non-null   object
dtypes: int64(1), object(4)
memory usage: 72.9+ KB

,Dim Product ID,Product ID,Product Type,Sub-Category,Product Name
0,1,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form..."
1,2,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs
2,3,OFF-LA-10003223,Office Supplies,Labels,Avery 508
3,4,OFF-ST-10002743,Office Supplies,Storage,Storage
4,5,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...

In [18]:
dim_customer_df.info()
dim_customer_df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 804 entries, 0 to 803
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Dim Customer ID  804 non-null    int64
 1   Customer ID      804 non-null    object
 2   Customer Name    804 non-null    object
 3   Segment          804 non-null    object
 4   Country/Region   804 non-null    object
 5   City             804 non-null    object
 6   State/Province   804 non-null    object
 7   Postal Code      804 non-null    object
 8   Region           804 non-null    object
dtypes: int64(1), object(8)
memory usage: 56.7+ KB

,Dim Customer ID,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region
0,1,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central
1,2,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central
2,3,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East
3,4,ME-17320,Maria Etezadi,Home Office,United States,Henderson,Kentucky,42420,South
4,5,JO-15145,Jack O'Briant,Corporate,United States,Athens,Georgia,30605,South

In [19]:
dim_order_df.info()
dim_order_df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5111 entries, 0 to 5110
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Dim Order ID  5111 non-null   int64
 1   Order ID      5111 non-null   object
 2   Order Date    5111 non-null   datetime64[ns]
 3   Ship Date     5111 non-null   datetime64[ns]
 4   Ship Mode     5111 non-null   object
 5   Is Returned   5111 non-null   bool
dtypes: bool(1), datetime64[ns](2), int64(1), object(2)
memory usage: 204.8+ KB

,Dim Order ID,Order ID,Order Date,Ship Date,Ship Mode,Is Returned
0,1,US-2019-103800,2019-01-03,2019-01-07,Standard Class,False
1,2,US-2019-112326,2019-01-04,2019-01-08,Standard Class,False
2,3,US-2019-141817,2019-01-05,2019-01-12,Standard Class,False
3,4,US-2019-167199,2019-01-06,2019-01-10,Standard Class,False
4,5,US-2019-106054,2019-01-06,2019-01-07,First Class,False

In [20]:
fact_sales_df.info()
fact_sales_df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PK-Artificial-ID  10194 non-null  object
 1   Dim Order ID      10194 non-null  int64
 2   Dim Product ID    10194 non-null  int64
 3   Dim Customer ID   10194 non-null  int64
 4   Price Per Unit    10194 non-null  float64
 5   Quantity          10194 non-null  int64
 6   Discount          10194 non-null  float64
 7   Profit            10194 non-null  float64
dtypes: float64(3), int64(4), object(1)
memory usage: 637.3+ KB

,PK-Artificial-ID,Dim Order ID,Dim Product ID,Dim Customer ID,Price Per Unit,Quantity,Discount,Profit
0,1#1,1,1,1,16.448,2,0.2,5.5512
1,2#2,2,2,2,3.540,2,0.8,-5.4870
2,2#3,2,3,2,11.784,3,0.2,4.2717
3,2#4,2,4,2,272.736,3,0.2,-64.7748
4,3#5,3,5,3,19.536,3,0.2,4.8840

### Notes
- Data imported successfully in dataframes
- Count of records look good and in line with excel total record counts
- What is artificial id in fact sales - why hashes? Is it even needed?
- IMP: Is there a way to clean product names? some of them look too long.

### Import these data sets into sql - ideally in a table in DWH - for now sql lite

In [21]:
# sql lite database
import sqlite3
conn = sqlite3.connect("retail_data.db")

In [22]:
# writing the dataframes to sqllite tables
dim_product_df.to_sql("dim_product", conn, if_exists = "replace", index = False)
dim_customer_df.to_sql("dim_customer", conn, if_exists = "replace", index = False)
dim_order_df.to_sql("dim_order", conn, if_exists = "replace", index = False)
fact_sales_df.to_sql("fact_sales", conn, if_exists = "replace", index = False)

10194

In [23]:
conn.close()

In [25]:
# verifying the tables
conn = sqlite3.connect("retail_data.db")

query = """
SELECT name
FROM sqlite_master
WHERE type = 'table';
"""

pd.read_sql(query, conn)

           name
0   dim_product
1  dim_customer
2     dim_order
3    fact_sales

In [26]:
# Test the tables
pd.read_sql("""
SELECT 
* FROM dim_product
LIMIT 5
""", conn)

,Dim Product ID,Product ID,Product Type,Sub-Category,Product Name
0,1,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form..."
1,2,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs
2,3,OFF-LA-10003223,Office Supplies,Labels,Avery 508
3,4,OFF-ST-10002743,Office Supplies,Storage,Storage
4,5,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...

In [27]:
pd.read_sql("""
SELECT 
count(*) FROM dim_product
""", conn)

   count(*)
0      1862

In [28]:
pd.read_sql("""
SELECT 
* FROM dim_customer
LIMIT 5
""", conn)

,Dim Customer ID,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region
0,1,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central
1,2,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central
2,3,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East
3,4,ME-17320,Maria Etezadi,Home Office,United States,Henderson,Kentucky,42420,South
4,5,JO-15145,Jack O'Briant,Corporate,United States,Athens,Georgia,30605,South

In [30]:
pd.read_sql("""
SELECT 
count(*) FROM dim_customer
""", conn)

   count(*)
0       804

In [31]:
pd.read_sql("""
SELECT 
* FROM dim_order
LIMIT 5
""", conn)

,Dim Order ID,Order ID,Order Date,Ship Date,Ship Mode,Is Returned
0,1,US-2019-103800,2019-01-03 00:00:00,2019-01-07 00:00:00,Standard Class,0
1,2,US-2019-112326,2019-01-04 00:00:00,2019-01-08 00:00:00,Standard Class,0
2,3,US-2019-141817,2019-01-05 00:00:00,2019-01-12 00:00:00,Standard Class,0
3,4,US-2019-167199,2019-01-06 00:00:00,2019-01-10 00:00:00,Standard Class,0
4,5,US-2019-106054,2019-01-06 00:00:00,2019-01-07 00:00:00,First Class,0

In [32]:
pd.read_sql("""
SELECT 
count(*) FROM dim_order
""", conn)

   count(*)
0      5111

In [33]:
pd.read_sql("""
SELECT 
* FROM fact_sales
LIMIT 5
""", conn)

,PK-Artificial-ID,Dim Order ID,Dim Product ID,Dim Customer ID,Price Per Unit,Quantity,Discount,Profit
0,1#1,1,1,1,16.448,2,0.2,5.5512
1,2#2,2,2,2,3.540,2,0.8,-5.4870
2,2#3,2,3,2,11.784,3,0.2,4.2717
3,2#4,2,4,2,272.736,3,0.2,-64.7748
4,3#5,3,5,3,19.536,3,0.2,4.8840

In [34]:
pd.read_sql("""
SELECT 
count(*) FROM fact_sales
""", conn)

   count(*)
0     10194

In [35]:
conn.close()

### Notes
- Data Successfully loaded in Tables
- Use sql lite and sql dialect further to clean data
- Once a clean data set is prepped - create an sql lite table to store it - final data source to be used in tableau will come from a view, materialised view - but here I can use sql lite table to replicate the same scenario

## Joins - identify appropriate joins and connect the tables

### A Star schema

In [80]:
# fact table has ids as keys for all the dimension tables
# join the tables to create a final sql query - that can be used to create a view/table to be fed to Tableau datasource
# also get the results of final resulting table in an excel that can be connected to Tableau datasource

conn = sqlite3.connect("retail_data.db")

In [84]:
conn.execute("""
DROP VIEW IF EXISTS view_retail_joined_dataset;
""")
conn.commit()

In [85]:
# order is a reserved statement in sql - can't use it as alias
# names of columns are already formatted properly - so no need to rename as they all look good for datasource consumption
# from my experience working with datasets - IDs are relevant in exposing datasets as they can be used for counts in Tableau datasource
# create counts in Tableau data source using ids - and then hide ids? - Specifically product id and customer id can be hiden in Tableau data source
# zip - as per my experience good for exposure because of very granular map visuals in Tableau. Hence, keeping it

# profit / revenue: derived metric - better in Tableau as if done here - taleau will confuse with reaggregations

# using CTE to only demonstrate that my personal preference as matter of best practice is to use them!

conn.execute("""

CREATE VIEW view_retail_joined_dataset AS 

WITH base AS (
    SELECT
        /* ---------- Product fields ---------- */
        product."Product ID",
        product."Product Type",
        product."Sub-Category",
        product."Product Name",

        /* ---------- Customer fields ---------- */
        customer."Customer ID",
        customer."Customer Name",
        customer."Segment",
        customer."Country/Region",
        customer."City",
        customer."State/Province",
        customer."Postal Code",
        customer."Region",

        /* ---------- Order fields ---------- */
        orders."Order ID",
        orders."Order Date",
        orders."Ship Date",
        orders."Ship Mode",
        CASE 
            WHEN orders."Is Returned" = 0 THEN 'Not Returned'
            WHEN orders."Is Returned" = 1 THEN 'Returned'
        ELSE 'NA' 
        END AS "Is Returned",

        /* ---------- Sales metrics ---------- */
        sales."Price Per Unit",
        sales.Quantity,
        sales.Discount,
        sales.Profit,

        /* ---------- Derived metrics ---------- */
        sales."Price Per Unit"
            * sales.Quantity
            * (1 - sales.Discount) AS Revenue,

        CAST(
            julianday(orders."Ship Date")
            - julianday(orders."Order Date")
            AS INTEGER
        ) AS "Shipping Days"

    FROM fact_sales AS sales

    -- Join product dimension
    LEFT JOIN dim_product AS product
        ON sales."Dim Product ID" = product."Dim Product ID"

    -- Join customer dimension
    LEFT JOIN dim_customer AS customer
        ON sales."Dim Customer ID" = customer."Dim Customer ID"

    -- Join order dimension
    LEFT JOIN dim_order AS orders
        ON sales."Dim Order ID" = orders."Dim Order ID"
)

SELECT
    *
FROM base
""")

In [86]:
conn.commit()

### View QA

In [87]:
pd.read_sql("""
SELECT * FROM view_retail_joined_dataset
""", conn)

,Product ID,Product Type,Sub-Category,Product Name,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,...,Order Date,Ship Date,Ship Mode,Is Returned,Price Per Unit,Quantity,Discount,Profit,Revenue,Shipping Days
0,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",DP-13000,Darren Powers,Consumer,United States,Houston,Texas,...,2019-01-03 00:00:00,2019-01-07 00:00:00,Standard Class,Not Returned,16.448,2,0.2,5.5512,26.3168,4
1,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,...,2019-01-04 00:00:00,2019-01-08 00:00:00,Standard Class,Not Returned,3.540,2,0.8,-5.4870,1.4160,4
2,OFF-LA-10003223,Office Supplies,Labels,Avery 508,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,...,2019-01-04 00:00:00,2019-01-08 00:00:00,Standard Class,Not Returned,11.784,3,0.2,4.2717,28.2816,4
3,OFF-ST-10002743,Office Supplies,Storage,Storage,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,...,2019-01-04 00:00:00,2019-01-08 00:00:00,Standard Class,Not Returned,272.736,3,0.2,-64.7748,654.5664,4
4,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,...,2019-01-05 00:00:00,2019-01-12 00:00:00,Standard Class,Not Returned,19.536,3,0.2,4.8840,46.8864,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,PO-18865,Patrick O'Donnell,Consumer,United States,Los Angeles,California,...,2022-12-30 00:00:00,2023-01-03 00:00:00,Standard Class,Not Returned,52.776,3,0.2,19.7910,126.6624,4
10190,OFF-BI-10004632,Office Supplies,Binders,Ibico Hi-Tech Manual Binding System,EB-13975,Erica Bern,Corporate,United States,Charlotte,North Carolina,...,2022-12-30 00:00:00,2023-01-03 00:00:00,Standard Class,Returned,20.720,2,0.2,6.4750,33.1520,4
10191,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,JM-15580,Jill Matthias,Consumer,United States,Baltimore,Maryland,...,2022-12-30 00:00:00,2023-01-03 00:00:00,Standard Class,Not Returned,3.024,3,0.2,-0.6048,7.2576,4
10192,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,PO-18865,Patrick O'Donnell,Consumer,United States,Los Angeles,California,...,2022-12-30 00:00:00,2023-01-03 00:00:00,Standard Class,Not Returned,90.930,7,0.0,2.7279,636.5100,4
10193,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,Prince Edward Island,...,2022-12-30 00:00:00,2023-01-03 00:00:00,Standard Class,Not Returned,3.024,3,0.2,-0.6048,7.2576,4

### Exporting the results in an excel as connecting Tableau to Sql lite in my localhost is not viable

In [88]:
final_joined_df = pd.read_sql("""
SELECT * FROM view_retail_joined_dataset
""", conn)

In [89]:
final_joined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product ID      10194 non-null  object
 1   Product Type    10194 non-null  object
 2   Sub-Category    10194 non-null  object
 3   Product Name    10194 non-null  object
 4   Customer ID     10194 non-null  object
 5   Customer Name   10194 non-null  object
 6   Segment         10194 non-null  object
 7   Country/Region  10194 non-null  object
 8   City            10194 non-null  object
 9   State/Province  10194 non-null  object
 10  Postal Code     10194 non-null  object
 11  Region          10194 non-null  object
 12  Order ID        10194 non-null  object
 13  Order Date      10194 non-null  object
 14  Ship Date       10194 non-null  object
 15  Ship Mode       10194 non-null  object
 16  Is Returned     10194 non-null  object
 17  Price Per Unit  10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
 21  Revenue         10194 non-null  float64
 22  Shipping Days   10194 non-null  int64
dtypes: float64(4), int64(2), object(17)
memory usage: 1.8+ MB

In [90]:
conn.close()

In [91]:
final_joined_df.to_excel("/Users/abhisheksingh/Downloads/archive/retail_data_joined_1.xlsx", sheet_name="Joined_Data", index=False)